from django.db import models


class Product(models.Model):
    PROGRAMNAME = models.CharField(max_length=100)
    PROGRAMURL = models.CharField(max_length=300)
    CATALOGNAME = models.CharField(max_length=130)
    LASTUPDATED = models.DateField(auto_now=True)
    NAME = models.CharField(max_length=160)
    KEYWORDS = models.CharField(max_length=300)
    DESCRIPTION = models.TextField()
    SKU = models.CharField(max_length=100)
    MANUFACTURER = models.CharField(max_length=160)
    MANUFACTURERID = models.CharField(max_length=64)
    UPC = models.CharField(max_length=100)
    ISBN = models.CharField(max_length=64)
    CURRENCY = models.CharField(max_length=3)
    SALEPRICE = models.DecimalField(max_digits=9, decimal_places=2)
    PRICE = models.DecimalField(max_digits=9, decimal_places=2)
    RETAILPRICE = models.DecimalField(max_digits=9, decimal_places=2)
    FROMPRICE = models.CharField(max_length=3)
    BUYURL = models.CharField(max_length=500)
    IMPRESSIONURL = models.CharField(max_length=300)
    IMAGEURL = models.CharField(max_length=300)
    ADVERTISERCATEGORY = models.CharField(max_length=300)
    SUBCATEGORY = models.CharField(max_length=300)
    THIRDPARTYID = models.CharField(max_length=64)
    THIRDPARTYCATEGORY = models.CharField(max_length=300)
    AUTHOR = models.CharField(max_length=130)
    ARTIST = models.CharField(max_length=130)
    TITLE = models.CharField(max_length=130)
    PUBLISHER = models.CharField(max_length=130)
    LABEL = models.CharField(max_length=130)
    FORMAT = models.CharField(max_length=64)
    SPECIAL = models.CharField(max_length=3)
    GIFT = models.CharField(max_length=3)
    PROMOTIONALTEXT = models.CharField(max_length=300)
    STARTDATE = models.DateField(auto_now=True)
    ENDDATE = models.DateField(auto_now=True)
    OFFLINE = models.CharField(max_length=3)
    ONLINE = models.CharField(max_length=3)
    INSTOCK = models.CharField(max_length=3)
    CONDITION = models.CharField(max_length=150)
    WARRANTY = models.CharField(max_length=11)
    STANDARDSHIPPINGCOST = models.DecimalField(max_digits=9, decimal_places=2)

    def __unicode__(self):
        return self.NAME